### ISSUE TITLE
lbdb-munge not executed when INMAIL_DB not set in lbdbrc

### ISSUE THREAD

**Issue by jerri** [RolandRosenfeld/lbdb#6]
If the variable `INMAIL_DB` is not set, then the default db value set in `m_inmail` is not visible to `lbdb-munge`. Therefore the database file just grows and grows.
It seems like `lbdb-munge` should use `m_inmail_db` instead of `INMAIL_DB`.
As a workaround just setting `INMAIL_DB` to the default value in `lbdbrc` fixes the problem. But people might not be aware of this.
I am using `lbdbq version 0.48.1`. But taking a look into the code in the git repo, the problem is still in the code.

**Comment by RolandRosenfeld** [comment]
You are right, this was a bug.
I just fixed this in commit [c16bb3efcd3a6d8909016aceffd19ac39cac0b3d](https://github.com/RolandRosenfeld/lbdb/commit/c16bb3efcd3a6d8909016aceffd19ac39cac0b3d)
